port: 1082
socks-port: 1081
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:8080
dns:
  enabled: true
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
  fallback:
    - 8.8.8.8
    - 8.8.4.4
    - tls://1.0.0.1:853
    - tls://dns.google:853
proxies:
proxy-groups: